config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :brewers, only: %i[index show]
  resources :beers, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: %i[index show]
  resources :subcategories, only: %i[show]
  resources :cart, only: %i[create destroy index update]
  resources :checkout, only: %i[index]
  resources :orders, only: %i[index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "beers#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  def login
    @login || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  has_one_attached :image

  belongs_to :brewer
  belongs_to :subcategory
  has_many :order_items

  validates :name, presence: true
  validates :price, presence: true
  validates :subcategory, presence: true
end

app/models/brewer.rb
class Brewer < ApplicationRecord
  belongs_to :country
  has_many :beer

  validates :name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories

  validates :name, presence: true, uniqueness: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :brewer

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :province
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :beer
  belongs_to :order
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :orders
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :beer

  validates :name, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(
        ["lower(username) = :value OR lower(email) = :value",
         { value: login.downcase }]
      ).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.includes(:subcategory, :brewer).order("name ASC").page(params[:page]).per(30)
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    if params[:category_id] != "0"
      @category = Category.find(params[:category_id])
      @subcategories = Subcategory.where("category_id = ?", params[:category_id])
      @beers = Beer.includes(:subcategory)
                   .where("name LIKE ? AND subcategory_id IN (?)",
                          wildcard_search,
                          @subcategories.ids)
                   .order("name ASC")
                   .page(params[:page]).per(30)
    else
      @category = "All Categories"
      @beers = Beer.includes(:subcategory)
                   .where("name LIKE ?", wildcard_search)
                   .order("name ASC")
                   .page(params[:page]).per(30)
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id]
    beers = session[:cart]

    if beers.keys.include?(id)
      session[:cart][id] += 1
    else
      session[:cart][id] = 1
    end

    beer = Beer.find(id)
    flash[:notice] = "#{beer.name} added to cart."

    if request.path == root_path
      redirect_to root_path
    else
      redirect_to cart_index_url
    end
  end

  def destroy
    id = params[:id]
    session[:cart].delete(id)
    beer = Beer.find(id)
    flash[:notice] = "#{beer.name} removed from cart."
    redirect_to cart_index_url
  end

  def update
    id = params[:id]
    beer_quantities = session[:cart]
    beer_quantities[id] -= 1
    session[:cart] = beer_quantities

    if beer_quantities[id].zero?
      destroy
    else
      redirect_to cart_index_url
    end
  end

  def index
    @provinces = Province.all.order("name ASC")
    @beer_quantities = session[:cart]
    @beers = Beer.find(@beer_quantities.keys.uniq)
    @subtotal = 0
    @beers.each do |beer|
      @subtotal += beer.price * @beer_quantities[beer.id.to_s]
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id)
    @order_items = OrderItem.includes(:beer).where(order_id: @orders.ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/cart/index.html.erb
<div class="container">
  <h3>Shopping Cart</h3>

  <div class="card">
    <div class="card-header">
      <h5 class="card-title">
        <%= pluralize(@beers.size, "Item") %>
      </h5>
    </div>
    <ul class="list-group">
      <% @beers.each do |beer| %>
        <li class="list-group-item">
          <p><%= beer.name %></p>
          <div class="row">
            <p class="col-3"><%= beer.size %></p>
            <p class="col-2"><%= number_to_currency(beer.price) %></p>
            <div class="col-2 d-inline-flex justify-content-between">
              <%= form_with url: cart_index_path do %>
                <%= hidden_field_tag(:id, beer.id) %>
                <%= button_tag "+" %>
              <% end %>

              <%= @beer_quantities[beer.id.to_s] %>

              <%= button_to cart_path(beer.id), method: :patch do %>
                <%= "-"%>
              <% end %>
            </div>
            <p class="col-3 text-right">Total: <%= number_to_currency(beer.price * @beer_quantities[beer.id.to_s])%></p>
            <div class="col-2">
              <%= button_to cart_path(beer.id), method: :delete do %>
                <%= "Remove" %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>

      <li class="list-group-item">
        <div class="row">
          <p class="col-10 text-right">Subtotal: <%= number_to_currency(@subtotal) %></p>
        </div>
      </li>
    <ul>
  </div>

  <div class="card">
    <div class="card-header">
      <h5 class="card-title">Customer Details</h5>
    </div>
    <div class="card-body">
      <%= form_with(url: checkout_index_path, method: :get, local: true) do %>
        <div class="row">
          <div class="col-sm-5  col-lg-6">
            <%= text_field_tag(:address, current_user[:address], placeholder: "Address", class:"w-100") %>
          </div>
          <div class="col-sm-5 col-lg-4">
            <%= select_tag(:province, options_from_collection_for_select(@provinces, "id", "name", current_user[:province_id]), class:"w-100") %>
          </div>
          <div class="col-2 text-right">
            <%= submit_tag("Checkout") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>