config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :brewers, only: %i[index show]
  resources :beers, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: %i[index show]
  resources :subcategories, only: %i[show]
  resources :cart, only: %i[create destroy index update]
  resources :checkout, only: %i[index]
  resources :orders, only: %i[index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "beers#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  def login
    @login || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  has_one_attached :image

  belongs_to :brewer
  belongs_to :subcategory
  has_many :order_items

  validates :name, presence: true
  validates :price, presence: true
  validates :subcategory, presence: true
end

app/models/brewer.rb
class Brewer < ApplicationRecord
  belongs_to :country
  has_many :beer

  validates :name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories

  validates :name, presence: true, uniqueness: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :brewer

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :province
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :beer
  belongs_to :order
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :orders
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :beer

  validates :name, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(
        ["lower(username) = :value OR lower(email) = :value",
         { value: login.downcase }]
      ).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.includes(:subcategory, :brewer).order("name ASC").page(params[:page]).per(30)
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    if params[:category_id] != "0"
      @category = Category.find(params[:category_id])
      @subcategories = Subcategory.where("category_id = ?", params[:category_id])
      @beers = Beer.includes(:subcategory)
                   .where("name LIKE ? AND subcategory_id IN (?)",
                          wildcard_search,
                          @subcategories.ids)
                   .order("name ASC")
                   .page(params[:page]).per(30)
    else
      @category = "All Categories"
      @beers = Beer.includes(:subcategory)
                   .where("name LIKE ?", wildcard_search)
                   .order("name ASC")
                   .page(params[:page]).per(30)
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id]
    beers = session[:cart]

    if beers.keys.include?(id)
      session[:cart][id] += 1
    else
      session[:cart][id] = 1
    end

    beer = Beer.find(id)
    flash[:notice] = "#{beer.name} added to cart."

    if request.path == root_path
      redirect_to root_path
    else
      redirect_to cart_index_url
    end
  end

  def destroy
    id = params[:id]
    session[:cart].delete(id)
    beer = Beer.find(id)
    flash[:notice] = "#{beer.name} removed from cart."
    redirect_to cart_index_url
  end

  def update
    id = params[:id]
    beer_quantities = session[:cart]
    beer_quantities[id] -= 1
    session[:cart] = beer_quantities

    if beer_quantities[id].zero?
      destroy
    else
      redirect_to cart_index_url
    end
  end

  def index
    @provinces = Province.all.order("name ASC")
    @beer_quantities = session[:cart]
    @beers = Beer.find(@beer_quantities.keys.uniq)
    @subtotal = 0
    @beers.each do |beer|
      @subtotal += beer.price * @beer_quantities[beer.id.to_s]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeggerBeerStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="container">
        <div class="row pt-3">
          <div class="col">
            <h1>Keggers Beer Store</h1>
          </div>
          <div class="col text-right">
            <% if current_user %>
              <% if current_user.name %>
                <%= current_user.name %>
              <% elsif current_user.username %>
                <%= current_user.username%>
              <% else %>
                <%= current_user.email %>
              <% end %>

              <%= link_to "Edit", edit_user_registration_path %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete%>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path %>
              <%= link_to "Login", new_user_session_path %>
            <% end %>
          </div>
        </div>
      </div>

      <div>
        <ul class="nav nav-tabs nav-fill justify-content-center pb2 pt-4">
          <li class="nav-item"><%= link_to "Beers", beers_path %></li>
          <li class="nav-item"><%= link_to "Brewers", brewers_path %></li>
          <li class="nav-item"><%= link_to "Categories", categories_path %></li>
          <% if current_user %>
            <li class="nav-item"><%= link_to "My orders", orders_path %></li>
          <% end %>
          <li><%= link_to image_tag("cart-icon.jpg", width: 40, alt: "Cart"), @cart_link %></li>
        </ul>
      </div>

      <%= form_with(url: search_beers_path, method: :get, local: true) do %>
        <div class="row pt-3">
          <div class="col text-right">
            <%= select_tag(:category_id, options_for_select(@dropdown_categories)) %>
          </div>
          <div class="col">
            <%= text_field_tag(:keywords, nil, placeholder: "Search Beers") %>
            <%= submit_tag("Search") %>
          </div>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>